In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('ex2/ex2data1.txt', header = None)

In [3]:
data.head()

0          1  2
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [4]:
X=data[[0,1]]
X.head()

0          1
0  34.623660  78.024693
1  30.286711  43.894998
2  35.847409  72.902198
3  60.182599  86.308552
4  79.032736  75.344376

In [5]:
y=data[2]
y.head()

0    0
1    0
2    0
3    1
4    1
Name: 2, dtype: int64

In [6]:
X.shape

(100, 2)

In [7]:
unos = np.ones(100)
X['independiente']=pd.DataFrame(unos)

In [8]:
X.head()

0          1  independiente
0  34.623660  78.024693            1.0
1  30.286711  43.894998            1.0
2  35.847409  72.902198            1.0
3  60.182599  86.308552            1.0
4  79.032736  75.344376            1.0

In [9]:
X = X.reindex(columns=['independiente',0,1])

In [10]:
X.head()

independiente          0          1
0            1.0  34.623660  78.024693
1            1.0  30.286711  43.894998
2            1.0  35.847409  72.902198
3            1.0  60.182599  86.308552
4            1.0  79.032736  75.344376

In [63]:
theta = np.array([-24,0.2,0.2])

In [64]:
X_array=np.array(X)

In [65]:
X_array[2]*theta

array([-24.        ,   7.16948175,  14.58043961])

In [66]:
X_matrix = np.matrix(X_array)

In [67]:
theta_matrix= np.matrix(theta)

In [68]:
X_matrix*theta_matrix.T

matrix([[ -1.47032951],
        [ -9.16365834],
        [ -2.25007864],
        [  5.2982303 ],
        [  6.8754225 ],
        [ -3.72007015],
        [  7.52361808],
        [  0.31575182],
        [  8.70387128],
        [  1.59324265],
        [  2.81736663],
        [ -2.87661568],
        [  7.75780334],
        [  9.41665614],
        [ -0.88497   ],
        [  4.63568046],
        [  0.36212276],
        [ -1.07491408],
        [  8.71772949],
        [  0.91094948],
        [ -1.95790683],
        [  7.09522834],
        [ -4.12188004],
        [ -8.31568208],
        [  5.37929029],
        [  2.44509432],
        [  1.00236194],
        [  2.38301183],
        [ -1.58273722],
        [ -3.24370305],
        [  2.83743535],
        [  4.49130067],
        [ -0.9528793 ],
        [  0.29565298],
        [ -1.71907165],
        [ -2.63020171],
        [  2.55698717],
        [  5.01700989],
        [ -0.72746636],
        [ -2.11572793],
        [  4.04208798],
        [ -4.319

In [69]:
X_matrix.shape

(100, 3)

In [70]:
theta_matrix.T.shape

(3, 1)

In [71]:
z= X_matrix*theta_matrix.T

sigmoid = 1/(1+np.exp(z))

In [72]:
sigmoid.sum()

35.709700510046552

In [73]:
np.log(np.exp(1))

1.0

In [74]:
J = 1/100*k

In [75]:
y_matrix = np.matrix(y)

In [76]:
(-y_matrix*np.log(sigmoid))

matrix([[ 349.58073718]])

In [77]:
(1-y_matrix)*np.log(1-sigmoid)

matrix([[-123.134634]])

In [78]:
k = float((-y_matrix*np.log(sigmoid))-(1-y_matrix)*np.log(1-sigmoid))

In [79]:
J = 1/100*k
J

4.7271537117484845

In [187]:
theta = np.array([-24,0.2,0.2])

In [134]:
X_array

array([[  1.        ,  34.62365962,  78.02469282],
       [  1.        ,  30.28671077,  43.89499752],
       [  1.        ,  35.84740877,  72.90219803],
       [  1.        ,  60.18259939,  86.3085521 ],
       [  1.        ,  79.03273605,  75.34437644],
       [  1.        ,  45.08327748,  56.31637178],
       [  1.        ,  61.10666454,  96.51142588],
       [  1.        ,  75.02474557,  46.55401354],
       [  1.        ,  76.0987867 ,  87.42056972],
       [  1.        ,  84.43281996,  43.53339331],
       [  1.        ,  95.86155507,  38.22527806],
       [  1.        ,  75.01365839,  30.60326323],
       [  1.        ,  82.30705337,  76.4819633 ],
       [  1.        ,  69.36458876,  97.71869196],
       [  1.        ,  39.53833914,  76.03681085],
       [  1.        ,  53.97105215,  89.20735014],
       [  1.        ,  69.07014406,  52.74046973],
       [  1.        ,  67.94685548,  46.67857411],
       [  1.        ,  70.66150955,  92.92713789],
       [  1.        ,  76.97878

In [135]:
y_array = np.array(y)
y_array

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1])

In [136]:
np.transpose(y_array)

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1])

In [190]:
z=np.dot(X_array,theta)
z

array([ -1.47032951,  -9.16365834,  -2.25007864,   5.2982303 ,
         6.8754225 ,  -3.72007015,   7.52361808,   0.31575182,
         8.70387128,   1.59324265,   2.81736663,  -2.87661568,
         7.75780334,   9.41665614,  -0.88497   ,   4.63568046,
         0.36212276,  -1.07491408,   8.71772949,   0.91094948,
        -1.95790683,   7.09522834,  -4.12188004,  -8.31568208,
         5.37929029,   2.44509432,   1.00236194,   2.38301183,
        -1.58273722,  -3.24370305,   2.83743535,   4.49130067,
        -0.9528793 ,   0.29565298,  -1.71907165,  -2.63020171,
         2.55698717,   5.01700989,  -0.72746636,  -2.11572793,
         4.04208798,  -4.31919789,   8.00245787,   0.59740178,
        -4.62590935,  -1.14326646,   5.53024699,  12.89988432,
         7.76837758,  12.05225341,   6.82158746,   8.05431159,
         2.78746318,  -5.01582874,  -3.98179301,  -2.12087436,
         9.30144134,   1.63514956,   4.81465252,   6.05000486,
         8.23110963,  -7.53867465,  -4.896942  ,  -8.06

In [138]:
h = 1/(1+np.exp(-z))

In [139]:
s = (-y_array*np.log(h)-(1-y_array)*np.log(1-h))

In [141]:
J=1/100*s.sum()
J

0.21833019382659785

In [160]:
for j in range(3):
    a1=(h-y_array)*X_array[:,j]
    theta[j]=1/100*a1.sum()
    
theta

array([ 0.04290299,  2.56623412,  2.64679737])

In [162]:
a1.sum()

264.67973710824333

In [172]:
h

array([  1.86892535e-01,   1.04767902e-04,   9.53426817e-02,
         9.95024445e-01,   9.98968205e-01,   2.36589577e-02,
         9.99460117e-01,   5.78288591e-01,   9.99834085e-01,
         8.31071833e-01,   9.43607101e-01,   5.33217140e-02,
         9.99572788e-01,   9.99918649e-01,   2.92148932e-01,
         9.90393672e-01,   5.89554197e-01,   2.54469685e-01,
         9.99836368e-01,   7.13194415e-01,   1.23693756e-01,
         9.99171635e-01,   1.59553035e-02,   2.44590126e-04,
         9.95410071e-01,   9.20201967e-01,   7.31522710e-01,
         9.15522663e-01,   1.70408175e-01,   3.75538198e-02,
         9.44665554e-01,   9.88918125e-01,   2.78306140e-01,
         5.73379509e-01,   1.51990780e-01,   6.72198018e-02,
         9.28041519e-01,   9.93419288e-01,   3.25750963e-01,
         1.07577522e-01,   9.82742291e-01,   1.31357121e-02,
         9.99665473e-01,   6.45061650e-01,   9.69973765e-03,
         2.41721140e-01,   9.96050650e-01,   9.99997502e-01,
         9.99577280e-01,

In [180]:
X_array[0]

array([  1.        ,  34.62365962,  78.02469282])

In [178]:
np.dot(A,A)

14

In [189]:
np.dot(X_array[0],theta)

-1.4703295120241258

In [188]:
theta

array([-24. ,   0.2,   0.2])